[package]
name = "pl0"
version = "0.1.0"
authors = ["Kyle Coffey <kylecoffey1999@gmail.com>"]
license = "GPL-3.0-only"
edition = "2021"

[dependencies]
nom = "7.1.1"
stacker = "0.1.15"
thiserror = "1.0.32"
